# Eksperimen

In [15]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [16]:
# read data
data = pd.read_csv('data_harga_beras.csv')
print(data)

     Tahun      Bulan       Kualitas     Harga
0     2013    Januari        Premium   7797.63
1     2013    Januari         Medium   7697.37
2     2013    Januari  Luar Kualitas   7545.32
3     2013   Februari        Premium   7773.26
4     2013   Februari         Medium   7645.05
..     ...        ...            ...       ...
346   2022    Agustus         Medium   9358.34
347   2022    Agustus  Luar Kualitas   9069.27
348   2022  September        Premium  10252.31
349   2022  September         Medium   9785.04
350   2022  September  Luar Kualitas   9465.63

[351 rows x 4 columns]


In [17]:
# convert data bulan dan kualitas to numeric
def convert_bulan(bulan):
  try :
    if(bulan == "Januari"):
      return 0
    elif(bulan == "Februari"):
      return 1
    elif(bulan == "Maret"):
      return 2
    elif(bulan == "April"):
      return 3
    elif(bulan == "Mei"):
      return 4
    elif(bulan == "Juni"):
      return 5
    elif(bulan == "Juli"):
      return 6
    elif(bulan == "Agustus"):
      return 7
    elif(bulan == "September"):
      return 8
    elif(bulan == "Oktober"):
      return 9
    elif(bulan == "November"):
      return 10
    elif(bulan == "Desember"):
      return 11
    else : 
      raise 

  except :
    print("Gagal mengkonversi bulan")
    return -1


def convert_kualitas(kualitas):
  try :
    if(kualitas == "Premium"):
      return 0
    elif(kualitas == "Medium"):
      return 1
    elif(kualitas == "Luar Kualitas"):
      return 2
    else : 
      raise 

  except :
    print("Gagal mengkonversi kualitas")
    return -1


data["Bulan"] = data["Bulan"].apply(convert_bulan)
data["Kualitas"] = data["Kualitas"].apply(convert_kualitas)

In [18]:
# training data
x = data.iloc [:300, : -1]
y = data.iloc [:300, -1 :]

In [19]:
print(x.to_numpy())

[[2013    0    0]
 [2013    0    1]
 [2013    0    2]
 [2013    1    0]
 [2013    1    1]
 [2013    1    2]
 [2013    2    0]
 [2013    2    1]
 [2013    2    2]
 [2013    3    0]
 [2013    3    1]
 [2013    3    2]
 [2013    4    0]
 [2013    4    1]
 [2013    4    2]
 [2013    5    0]
 [2013    5    1]
 [2013    5    2]
 [2013    6    0]
 [2013    6    1]
 [2013    6    2]
 [2013    7    0]
 [2013    7    1]
 [2013    7    2]
 [2013    8    0]
 [2013    8    1]
 [2013    8    2]
 [2013    9    0]
 [2013    9    1]
 [2013    9    2]
 [2013   10    0]
 [2013   10    1]
 [2013   10    2]
 [2013   11    0]
 [2013   11    1]
 [2013   11    2]
 [2014    0    0]
 [2014    0    1]
 [2014    0    2]
 [2014    1    0]
 [2014    1    1]
 [2014    1    2]
 [2014    2    0]
 [2014    2    1]
 [2014    2    2]
 [2014    3    0]
 [2014    3    1]
 [2014    3    2]
 [2014    4    0]
 [2014    4    1]
 [2014    4    2]
 [2014    5    0]
 [2014    5    1]
 [2014    5    2]
 [2014    6    0]
 [2014    

In [20]:
print(y)

       Harga
0    7797.63
1    7697.37
2    7545.32
3    7773.26
4    7645.05
..       ...
295  9153.68
296  8741.80
297  9549.76
298  8978.86
299  8675.23

[300 rows x 1 columns]


In [21]:
# test data
x_test = data.iloc [300:, : -1]
y_test = data.iloc[300:, -1 :]

In [22]:
print(x_test)

     Tahun  Bulan  Kualitas
300   2021      4         0
301   2021      4         1
302   2021      4         2
303   2021      5         0
304   2021      5         1
305   2021      5         2
306   2021      6         0
307   2021      6         1
308   2021      6         2
309   2021      7         0
310   2021      7         1
311   2021      7         2
312   2021      8         0
313   2021      8         1
314   2021      8         2
315   2021      9         0
316   2021      9         1
317   2021      9         2
318   2021     10         0
319   2021     10         1
320   2021     10         2
321   2021     11         0
322   2021     11         1
323   2021     11         2
324   2022      0         0
325   2022      0         1
326   2022      0         2
327   2022      1         0
328   2022      1         1
329   2022      1         2
330   2022      2         0
331   2022      2         1
332   2022      2         2
333   2022      3         0
334   2022      3   

In [23]:
print(y_test)

        Harga
300   9627.08
301   8909.50
302   8710.44
303   9537.16
304   8906.67
305   8694.95
306   9401.61
307   8886.90
308   8481.43
309   9499.36
310   8915.75
311   8688.77
312   9455.56
313   8962.39
314   8588.59
315   9449.47
316   9010.82
317   8630.83
318   9539.29
319   9071.94
320   8711.19
321   9672.54
322   9128.44
323   8888.50
324   9824.23
325   9381.24
326   9038.14
327   9826.88
328   9358.61
329   9061.74
330   9786.63
331   9323.35
332   9061.05
333   9576.75
334   9104.35
335   8853.24
336   9512.63
337   9065.18
338   8902.12
339   9497.40
340   9007.86
341   8848.66
342   9628.57
343   9091.92
344   8905.52
345   9901.15
346   9358.34
347   9069.27
348  10252.31
349   9785.04
350   9465.63


## with Random Forest Regression

In [24]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor
  
# create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0, criterion="absolute_error", max_features=3)
  
# fit the regressor with x and y data
regressor.fit(x.to_numpy(), y.values.ravel())  

RandomForestRegressor(criterion='absolute_error', max_features=3,
                      random_state=0)

test to train dataset

In [27]:
Y_pred = regressor.predict(x.to_numpy())
Y_pred

array([ 7772.9353 ,  7669.10905,  7466.61905,  7746.3424 ,  7625.53435,
        7366.75445,  7617.4552 ,  7494.77775,  7112.35035,  7463.0626 ,
        7344.39455,  6942.56435,  7503.5291 ,  7322.91955,  6895.22155,
        7553.6901 ,  7408.00405,  7074.08645,  7711.6558 ,  7540.5262 ,
        7268.5853 ,  7736.0445 ,  7551.9144 ,  7393.8284 ,  7755.2343 ,
        7631.1046 ,  7374.3046 ,  7821.7638 ,  7694.7293 ,  7432.7598 ,
        7886.5709 ,  7743.505  ,  7569.1709 ,  7936.7688 ,  7847.8945 ,
        7680.3778 ,  8210.89315,  8043.20275,  7941.09745,  8249.02335,
        8098.16185,  8013.07245,  8182.92255,  8074.34645,  8022.74725,
        8007.63485,  7893.43895,  7723.36675,  8012.38035,  7834.64905,
        7678.40635,  8115.87435,  7837.43205,  7694.63535,  8192.15555,
        7928.00825,  7664.32255,  8279.92795,  8024.47065,  7709.95925,
        8302.33425,  8098.73055,  7635.94695,  8357.1873 ,  8145.0786 ,
        7723.5884 ,  8503.8923 ,  8340.3441 ,  7995.7697 ,  8891

In [28]:
from sklearn.metrics import mean_absolute_percentage_error
print(mean_absolute_percentage_error(y.to_numpy(), Y_pred))

0.004568289636308643


test to test dataset

In [29]:
Y_pred = regressor.predict(x_test.to_numpy())
Y_pred

array([9645.98  , 9200.0025, 8755.2806, 9666.4813, 9191.1999, 8748.4136,
       9683.2601, 9169.9915, 8745.1347, 9690.9336, 9175.2288, 8780.4526,
       9694.9664, 9290.835 , 8922.3807, 9693.4598, 9379.2835, 9058.3455,
       9660.1192, 9373.9918, 9071.7083, 9683.9049, 9397.5883, 9079.6329,
       9791.7666, 9411.8963, 9117.6666, 9792.602 , 9408.8437, 9163.9477,
       9653.1511, 9273.5413, 8924.9368, 9637.2127, 9172.5548, 8752.8905,
       9645.98  , 9200.0025, 8755.2806, 9666.4813, 9191.1999, 8748.4136,
       9683.2601, 9169.9915, 8745.1347, 9690.9336, 9175.2288, 8780.4526,
       9694.9664, 9290.835 , 8922.3807])

In [30]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_percentage_error(y_test.to_numpy(), Y_pred))

0.02073304071406128


test to 1 data

In [31]:
Y_pred = regressor.predict([[2013,    4,    2]])
print(Y_pred)

[6895.22155]


In [32]:
from sklearn.metrics import mean_absolute_percentage_error
print(mean_absolute_percentage_error(y.to_numpy()[0], Y_pred))


0.11572855470187793


## with linear regression

In [33]:
from sklearn.linear_model import LinearRegression
 
model_LR = LinearRegression()
model_LR.fit(x.to_numpy(), y)


LinearRegression()

test to test dataset

In [34]:
Y_pred = model_LR.predict(x_test.to_numpy())
print(mean_absolute_percentage_error(y_test.to_numpy(), Y_pred))

0.09435128166740835


## with KNN

In [35]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor()
neigh.fit(x.to_numpy(), y)

KNeighborsRegressor()

test to test dataset

In [36]:
Y_pred = neigh.predict(x_test.to_numpy())
print(mean_absolute_percentage_error(y_test.to_numpy(), Y_pred))

0.028702441488998965


# Model yang dipilih adalah Random Forest Regression, karena memberikan skor MAPE yang paling baik

save model

In [25]:
import pickle
# save to file model.pkl
pickle.dump(regressor, open('model.pkl', 'wb'))

In [ ]:
# load model
pickled_model = pickle.load(open('model.pkl', 'rb'))

# test predict
pickled_model.predict(x.to_numpy())